name = input("type your name")
surname = input("type your surname")
age = input("type your age")
print(name )
print(surname )
print(age )
num1 = int(input("type one number "))
num2 = int(input("type one number "))
print(num1 + num2)