print(True or False)
print(True and False)
print(5>2)
print(6<11)
print(9==9)
print(9<=9)
print(20>=3)
print(20!=2)
num=int(input("pls enter  number"))
num2=int(input("pls enter  number"))
print(num <= num2)
print(num >= num2)

num=int(input("pls enter  number"))
print(num == 10)